name: Update pyproject.toml Version

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  update-version:
    if: startsWith(github.event.comment.body, 'update-version=')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from comment
        id: extract_version
        run: |
          echo "Requested comment: ${{ github.event.comment.body }}"
          VERSION=$(echo "${{ github.event.comment.body }}" | sed 's/update-version=//')
          echo "VERSION: $VERSION"
          echo "::set-output name=version::$VERSION"
      
      - name: Update version in pyproject.toml
        run: |
          sed -i 's/version = "[^"]*"/version = "${{ steps.extract_version.outputs.version }}"/' pyproject.toml

      - name: Display pyproject.toml after modification
        run: cat pyproject.toml
          
    #   - name: Commit changes
    #     run: |
    #       git config --local user.name "github-actions[bot]"
    #       git config --local user.email "github-actions[bot]@users.noreply.github.com"
    #       git checkout develop
    #       git pull origin develop
    #       git checkout -b update-version-${{ steps.extract_version.outputs.version }}
    #       git branch  # 現在のブランチを確認
    #       git commit -am "Update version to ${{ steps.extract_version.outputs.version }}"
    #       git push origin update-version-${{ steps.extract_version.outputs.version }}
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout develop
          git checkout -b update-version-${{ steps.extract_version.outputs.version }}  # 新しいブランチを直接 develop から作成
          git add pyproject.toml
          git commit -m "Update version to ${{ steps.extract_version.outputs.version }}"
          git push origin -u update-version-${{ steps.extract_version.outputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #branch: update-version-${{ steps.extract_version.outputs.version }}
          base: develop
          title: "Update version to ${{ steps.extract_version.outputs.version }}"
          body: "This PR updates the version in pyproject.toml to ${{ steps.extract_version.outputs.version }}."
